# Generated by Django 5.0.6 on 2024-07-10 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='country',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_subscribed',
        ),
        migrations.RemoveField(
            model_name='user',
            name='loyalty_points',
        ),
        migrations.RemoveField(
            model_name='user',
            name='subscription_end_date',
        ),
        migrations.RemoveField(
            model_name='user',
            name='subscription_start_date',
        ),
    ]
